name: urban-heat-fig1
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - cartopy
  - geopandas
  - shapely
  - rasterio
  - statsmodels
  - pyyaml
